### ISSUE TITLE
Image uploading issue

### ISSUE THREAD

**Issue by inder4u** [a-ono/redmine_ckeditor#127]
When i upload image it show no error. But the (+) always turn red. I have tried with .bmp,.jpeg,.png all same red (+) icon.

Using redmine 2.5.2.

**Comment by asinteg-daehn** [comment]
I encounter the same problem with Debian Wheezy + Redmine 2.6.1 and Apache 2.

Inside the production.log there is an error message:
```
Started POST "/redmine/rich/files?authenticity_token=t%2B%2BxS2IqxHGiDlRQA7p0Vmfx5No0Y%2FGAsfoHvQdVBZM%3D&simplified_type=image&scoped=true&scope_type=Project&scope_id=47&qqfile=IMG_1721.JPG" for 192.168.10.30 at 20
14-11-11 14:32:38 +0100
Processing by Rich::FilesController#create as HTML
  Parameters: {"file"=>#<ActionDispatch::Http::UploadedFile:0xa038644 @original_filename="IMG_1721.JPG", @content_type="application/octet-stream", @headers=nil, @tempfile=#<File:/tmp/raw-upload.20141111-3994-zgjoij>
>, "authenticity_token"=>"t++xS2IqxHGiDlRQA7p0Vmfx5No0Y/GAsfoHvQdVBZM=", "simplified_type"=>"image", "scoped"=>"true", "scope_type"=>"Project", "scope_id"=>"47", "qqfile"=>"IMG_1721.JPG"}
  Current user: christian (id=2)
Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/8e42ac41a685f874f5b184279f27dbb620141111-3994-m2eyf9.JPG[0]' 2>/dev/null
Command :: identify -format %m '/tmp/8e42ac41a685f874f5b184279f27dbb620141111-3994-m2eyf9.JPG[0]'
Command :: identify -format %m '/tmp/8e42ac41a685f874f5b184279f27dbb620141111-3994-m2eyf9.JPG[0]'
Command :: identify -format %m '/tmp/8e42ac41a685f874f5b184279f27dbb620141111-3994-m2eyf9.JPG[0]'
Command :: convert '/tmp/8e42ac41a685f874f5b184279f27dbb620141111-3994-m2eyf9.JPG[0]' -auto-orient -resize "x100" -crop "100x100+16+0" +repage '/tmp/8e42ac41a685f874f5b184279f27dbb620141111-3994-m2eyf920141111-3994-
4a8qpe'
Command :: file -b --mime '/tmp/8e42ac41a685f874f5b184279f27dbb620141111-3994-m2eyf920141111-3994-4a8qpe'
Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/8e42ac41a685f874f5b184279f27dbb620141111-3994-m2eyf9.JPG[0]' 2>/dev/null
Command :: identify -format %m '/tmp/8e42ac41a685f874f5b184279f27dbb620141111-3994-m2eyf9.JPG[0]'
Command :: identify -format %m '/tmp/8e42ac41a685f874f5b184279f27dbb620141111-3994-m2eyf9.JPG[0]'
Command :: identify -format %m '/tmp/8e42ac41a685f874f5b184279f27dbb620141111-3994-m2eyf9.JPG[0]'
Command :: convert '/tmp/8e42ac41a685f874f5b184279f27dbb620141111-3994-m2eyf9.JPG[0]' -auto-orient -resize "x100" -crop "100x100+16+0" +repage '/tmp/8e42ac41a685f874f5b184279f27dbb620141111-3994-m2eyf920141111-3994-
fcounw'
Command :: file -b --mime '/tmp/8e42ac41a685f874f5b184279f27dbb620141111-3994-m2eyf920141111-3994-fcounw'
Completed 500 Internal Server Error in 1494.0ms

Errno::EACCES (Permission denied - /var/redmine-2.6/public/system):
  /usr/lib/ruby/1.9.1/fileutils.rb:247:in `mkdir'
  /usr/lib/ruby/1.9.1/fileutils.rb:247:in `fu_mkdir'
  /usr/lib/ruby/1.9.1/fileutils.rb:221:in `block (2 levels) in mkdir_p'
  /usr/lib/ruby/1.9.1/fileutils.rb:219:in `reverse_each'
  /usr/lib/ruby/1.9.1/fileutils.rb:219:in `block in mkdir_p'
  /usr/lib/ruby/1.9.1/fileutils.rb:205:in `each'
  /usr/lib/ruby/1.9.1/fileutils.rb:205:in `mkdir_p'
  paperclip (3.5.4) lib/paperclip/storage/filesystem.rb:38:in `block in flush_writes'
  paperclip (3.5.4) lib/paperclip/storage/filesystem.rb:37:in `each'
  paperclip (3.5.4) lib/paperclip/storage/filesystem.rb:37:in `flush_writes'
  paperclip (3.5.4) lib/paperclip/attachment.rb:225:in `save'
  paperclip (3.5.4) lib/paperclip/has_attached_file.rb:82:in `block in add_active_record_callbacks'
  activesupport (3.2.20) lib/active_support/callbacks.rb:405:in `_run__561784281__save__359255344__callbacks'
```

I FIXED the error by creating `.../redmine/public/system/` and changing `system/` to owner `www-data` (Apache user). Now uploading works and all images are stored in a hughe and twice named complex dir structure in system:

```
public/system/:
rich

public/system/rich:
public/system/rich/rich_files:
public/system/rich/rich_files/rich_files:
public/system/rich/rich_files/rich_files/000:
public/system/rich/rich_files/rich_files/000/000:
public/system/rich/rich_files/rich_files/000/000/001:
public/system/rich/rich_files/rich_files/000/000/001/original:
example.png

public/system/rich/rich_files/rich_files/000/000/001/rich_thumb:
example.png

public/system/rich/rich_files/rich_files/000/000/001/thumb:
example.png
```

Why are the files not stored under the default `.../redmine/files/` directory?

ciao,
Chris

**Comment by a-ono** [comment]
`public/system/rich` is upload directory of [rich](https://github.com/bastiaanterhorst/rich) gem.
It requires write permission for the user who runs Redmine.
