### ISSUE TITLE
File upload fail

### ISSUE THREAD

**Issue by fuksman** [a-ono/redmine_ckeditor#148]
Hi.

I can't upload file using CKEditor. 
```
Environment:
  Redmine version                2.6.1.stable.13994
  Ruby version                   2.0.0-p594 (2014-10-27) [x86_64-linux]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               Mysql2
```
```
Redmine plugins:
  a_common_libs                  1.1.2
  ajax_counters                  0.0.1
  clipboard_image_paste          1.9
  quick_edit                     0.0.6
  redmine_agile                  1.3.5
  redmine_ckeditor               1.0.19
  redmine_knowledgebase          3.0.7
  redmine_people                 0.1.8
  redmine_slack                  0.1
  redmine_stats                  0.0.2
  unread_issues                  1.0.0
  wiki_external_filter           0.0.2
```
```
Errno::EACCES (Permission denied - /srv/redmine/public/system/rich/rich_files/rich_files/000):
  /usr/local/rvm/rubies/ruby-2.0.0-p594/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir'
  /usr/local/rvm/rubies/ruby-2.0.0-p594/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
  /usr/local/rvm/rubies/ruby-2.0.0-p594/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
  /usr/local/rvm/rubies/ruby-2.0.0-p594/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
  /usr/local/rvm/rubies/ruby-2.0.0-p594/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
  /usr/local/rvm/rubies/ruby-2.0.0-p594/lib/ruby/2.0.0/fileutils.rb:203:in `each'
  /usr/local/rvm/rubies/ruby-2.0.0-p594/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
  paperclip (3.5.4) lib/paperclip/storage/filesystem.rb:38:in `block in flush_writes'
  paperclip (3.5.4) lib/paperclip/storage/filesystem.rb:37:in `each'
  paperclip (3.5.4) lib/paperclip/storage/filesystem.rb:37:in `flush_writes'
  paperclip (3.5.4) lib/paperclip/attachment.rb:225:in `save'
  paperclip (3.5.4) lib/paperclip/has_attached_file.rb:82:in `block in add_active_record_callbacks'
...
```

**Comment by a-ono** [comment]
You must have write permission on `redmine/public/system`.
Please see #70, #127

**Comment by fuksman** [comment]
I've changed permissions but upload still fails.

```
drwxrwxrwx  3 www-data www-data 4096 Feb  2 17:52 files
drwxrwxrwx  2 www-data www-data 4096 Feb  2 08:17 log
drwxrwxrwx  8 www-data www-data 4096 Feb  2 09:20 tmp
drwxrwxrwx 12 www-data www-data 4096 Feb  6 20:12 plugin_assets
drwxrwxrwx 3 root root 4096 Feb  9 16:10 rich
```

```
Errno::EACCES (Permission denied - /srv/redmine/public/system/rich/rich_files/rich_files/000):
  /usr/local/rvm/rubies/ruby-2.0.0-p594/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir'
  /usr/local/rvm/rubies/ruby-2.0.0-p594/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
  /usr/local/rvm/rubies/ruby-2.0.0-p594/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
  /usr/local/rvm/rubies/ruby-2.0.0-p594/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
  /usr/local/rvm/rubies/ruby-2.0.0-p594/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
  /usr/local/rvm/rubies/ruby-2.0.0-p594/lib/ruby/2.0.0/fileutils.rb:203:in `each'
  /usr/local/rvm/rubies/ruby-2.0.0-p594/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
  paperclip (3.5.4) lib/paperclip/storage/filesystem.rb:38:in `block in flush_writes'
  paperclip (3.5.4) lib/paperclip/storage/filesystem.rb:37:in `each'
  paperclip (3.5.4) lib/paperclip/storage/filesystem.rb:37:in `flush_writes'
  paperclip (3.5.4) lib/paperclip/attachment.rb:225:in `save'
  paperclip (3.5.4) lib/paperclip/has_attached_file.rb:82:in `block in add_active_record_callbacks'
```

**Comment by a-ono** [comment]
Please create uploads directory and change owner.
```
mkdir -p /srv/redmine/public/system
chown -R www-data:www-data /srv/redmine/public/system
```

**Comment by fuksman** [comment]
Thanks!
