### ISSUE TITLE
The conversion of single projects not possible

### ISSUE THREAD

**Issue by hriekehof** [a-ono/redmine_ckeditor#165]
Hi,

i want to use the migration task to convert a single project from textile to html. But when i use the migration task for this it always asks to convert ALL projects. Then i abort and i get the following error message afterwards.
**Don't know how to build task '[PROJECT=project_ident]'**

Am i doing something wrong ? Is use this call to start the rake task:

**rake redmine_ckeditor:migrate RAILS_ENV=production [PROJECT=project_ident] [FROM=textile] [TO=html]**

This is the complete output with --trace:

```
root@redmine www/redmine# rake redmine_ckeditor:migrate RAILS_ENV=production [PROJECT=schoepsmk] [FROM=textile] [TO=html] --trace
** Invoke redmine_ckeditor:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine_ckeditor:migrate
*** WARNING ***
It is strongly recommended to backup your database before migration, because it cannot be rolled back completely.
***************
projects: ALL
migration: textile to html
Do you want to continue? (type 'y' to continue): n
Cancelled
rake aborted!
Don't know how to build task '[PROJECT=schoepsmk]'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/rake-10.4.2/lib/rake/task_manager.rb:62:in `[]'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/rake-10.4.2/lib/rake/application.rb:149:in `invoke_task'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p448/bin/rake:19:in `load'
/usr/local/rvm/gems/ruby-1.9.3-p448/bin/rake:19:in `<main>'
/usr/local/rvm/gems/ruby-1.9.3-p448/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-1.9.3-p448/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by a-ono** [comment]
Square brackets(`[]`) means that arguments are optional.
You should not include brackets. 
<pre>
rake redmine_ckeditor:migrate RAILS_ENV=production PROJECT=schoepsmk
</pre>

**Comment by hriekehof** [comment]
Thanks ;)
