### ISSUE TITLE
Cannot add plugins

### ISSUE THREAD

**Issue by PabloIgnacio** [a-ono/redmine_ckeditor#244]
Hi a-ono,
I am trying to add a plugin following your instructions:

> Plugins
> You can download plugins from Add-ons Repository. To activate the plugin you have to copy the plugin directory into assets/ckeditor-contrib/plugins and restart Redmine, then configure toolbar settings.

And I receive this error:

```
Could not create directory /opt/bitnami/apps/redmineplusagile/htdocs/public/plugin_assets/redmine_ckeditor/ckeditor-contrib/plugins/stylesheetparser: Permission denied @ dir_s_mkdir - /opt/bitnami/apps/redmineplusagile/htdocs/public/plugin_assets/redmine_ckeditor/ckeditor-contrib/plugins/stylesheetparser (RuntimeError)
  /opt/bitnami/apps/redmineplusagile/htdocs/lib/redmine/plugin.rb:406:in `rescue in block in mirror_assets'
  /opt/bitnami/apps/redmineplusagile/htdocs/lib/redmine/plugin.rb:403:in `block in mirror_assets'
  /opt/bitnami/apps/redmineplusagile/htdocs/lib/redmine/plugin.rb:399:in `each'
  /opt/bitnami/apps/redmineplusagile/htdocs/lib/redmine/plugin.rb:399:in `mirror_assets'
  /opt/bitnami/apps/redmineplusagile/htdocs/lib/redmine/plugin.rb:428:in `block in mirror_assets'
  /opt/bitnami/apps/redmineplusagile/htdocs/lib/redmine/plugin.rb:427:in `each'
  /opt/bitnami/apps/redmineplusagile/htdocs/lib/redmine/plugin.rb:427:in `mirror_assets'
  /opt/bitnami/apps/redmineplusagile/htdocs/config/initializers/30-redmine.rb:23:in `<top (required)>'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in `load_config_initializer'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `each'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
  /opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
  /opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
  /opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:418:in `block (2 levels) in each_strongly_connected_component_from'
  /opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
  /opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:417:in `block in each_strongly_connected_component_from'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
  /opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:411:in `call'
  /opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:411:in `each_strongly_connected_component_from'
  /opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
  /opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:345:in `each'
  /opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:345:in `call'
  /opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
  /opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
  /opt/bitnami/ruby/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
  /opt/bitnami/apps/redmineplusagile/htdocs/config/environment.rb:14:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `instance_eval'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.6/helper-scripts/rack-preloader.rb:111:in `eval'
  /opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.6/helper-scripts/rack-preloader.rb:111:in `preload_app'
  /opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.6/helper-scripts/rack-preloader.rb:157:in `<module:App>'
  /opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.6/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
  /opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.6/helper-scripts/rack-preloader.rb:28:in `<main>'

```

I have checked permissions and ownership, and there is no difference with the preinstalled plugins. So, I have no idea why it says "Permission Denied".
Do you have any idea about what is the problem?

Thank in advance!

Best Regards,
Pablo.

**Comment by a-ono** [comment]
Please check permissions of /opt/bitnami/apps/redmineplusagile/htdocs/public.

**Comment by PabloIgnacio** [comment]
That's it.
Thank you!

**Comment by PabloIgnacio** [comment]
That's it!
Thank you!!!
