### ISSUE TITLE
Install Error in Redmine 3.4.3

### ISSUE THREAD

**Issue by serenabenny** [a-ono/redmine_ckeditor#263]
```
Using rake 12.3.0
Using i18n 0.7.0
Using minitest 5.10.3
Using thread_safe 0.3.6
Using builder 3.2.3
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using crass 1.0.3
Using rack 1.6.8
Using mini_mime 1.0.0
Using arel 6.0.4
Using thor 0.20.0
Using concurrent-ruby 1.0.5
Using bundler 1.15.1
Using coderay 1.1.2
Using request_store 1.0.5
Using mime-types-data 3.2016.0521
Using public_suffix 3.0.1
Using mimemagic 0.3.2
Using rubyzip 1.0.0
Using htmlentities 4.3.4
Using rbpdf-font 1.19.1
Using net-ldap 0.12.1
Using ruby-openid 2.3.0
Using rmagick 2.16.0
Using redcarpet 3.4.0
Using mysql2 0.4.10
Using liquid 2.6.3
Using kaminari-core 1.1.1
Using multi_json 1.12.2
Using rb-fsevent 0.10.2
Using ffi 1.9.18
Using tilt 2.0.8
Using climate_control 0.2.0
Using pandoc-ruby 2.0.2
Using ruby-ole 1.2.12.1
Using dalli 2.7.6
Using memcachier 0.0.2
Using tzinfo 1.2.4
Using nokogiri 1.7.2
Using rack-test 0.6.3
Using mail 2.7.0
Using sprockets 3.7.1
Using mime-types 3.1
Using addressable 2.5.2
Using zip-zip 0.3
Using rbpdf 1.19.3
Using rack-openid 1.4.2
Using redmine_crm 0.0.32
Using rack-raw-upload 1.1.1
Using rb-inotify 0.9.10
Using cocaine 0.5.8
Using spreadsheet 1.1.5
Using activesupport 4.2.8
Using loofah 2.1.1
Using axlsx 2.0.1
Using css_parser 1.6.0
Using sass-listen 4.0.0
Using roo 1.13.2
Using rails-deprecated_sanitizer 1.0.3
Using globalid 0.4.1
Using activemodel 4.2.8
Using rails-html-sanitizer 1.0.3
Using roadie 3.2.2
Using sass 3.5.3
Using rails-dom-testing 1.0.8
Using activejob 4.2.8
Using activerecord 4.2.8
Using protected_attributes 1.1.4
Using paperclip 4.2.4
Using actionview 4.2.8
Using kaminari-activerecord 1.1.1
Using actionpack 4.2.8
Using kaminari-actionview 1.1.1
Using actionmailer 4.2.8
Using railties 4.2.8
Using sprockets-rails 3.2.1
Using actionpack-xml_parser 1.0.2
Using axlsx_rails 0.5.1
Using kaminari 1.1.1
Using jquery-rails 3.1.4
Using roadie-rails 1.1.1
Using rails 4.2.8
Using sass-rails 5.0.7
Using rich 1.4.8 from https://github.com/a-ono/rich.git (at master@93d1dd9)
Bundle complete! 43 Gemfile dependencies, 85 gems now installed.
Gems in the groups development, test, postgresql and sqlite were not installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```
**Error log**

```
[ 2017-12-14 02:29:07.5529 1386/7ffa025d0700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /opt/redmine/redmine: An error occurred while starting up the preloader.
  Error ID: 1bbd191a
  Error details saved to: /tmp/passenger-error-W467MH.html
  Message from application: <p>It looks like Bundler could not find a gem. Maybe you didn't install all the gems that this application needs. To install your gems, please run:</p>

  <pre class="commands">bundle install</pre>

<p>If that didn't work, then the problem is probably caused by your application being run under a different environment than it's supposed to. Please check the following:</p>

<ol>
  <li>Is this app supposed to be run as the <code>nobody</code> user?</li>
  <li>Is this app being run on the correct Ruby interpreter? Below you will
      see which Ruby interpreter Phusion Passenger attempted to use.</li>
</ol>

<p>-------- The exception is as follows: -------</p>
https://github.com/a-ono/rich.git (at master@93d1dd9) is not yet checked out. Run `bundle install` first. (Bundler::GitError)
<pre>  /var/lib/gems/2.3.0/gems/bundler-1.16.0/lib/bundler/source/git.rb:202:in `rescue in load_spec_files&#39;
  /var/lib/gems/2.3.0/gems/bundler-1.16.0/lib/bundler/source/git.rb:199:in `load_spec_files&#39;
  /var/lib/gems/2.3.0/gems/bundler-1.16.0/lib/bundler/source/path.rb:100:in `local_specs&#39;
  /var/lib/gems/2.3.0/gems/bundler-1.16.0/lib/bundler/source/git.rb:166:in `specs&#39;
  /var/lib/gems/2.3.0/gems/bundler-1.16.0/lib/bundler/lazy_specification.rb:76:in `__materialize__&#39;
  /var/lib/gems/2.3.0/gems/bundler-1.16.0/lib/bundler/spec_set.rb:85:in `block in materialize&#39;
  /var/lib/gems/2.3.0/gems/bundler-1.16.0/lib/bundler/spec_set.rb:82:in `map!&#39;
  /var/lib/gems/2.3.0/gems/bundler-1.16.0/lib/bundler/spec_set.rb:82:in `materialize&#39;
  /var/lib/gems/2.3.0/gems/bundler-1.16.0/lib/bundler/definition.rb:170:in `specs&#39;
  /var/lib/gems/2.3.0/gems/bundler-1.16.0/lib/bundler/definition.rb:237:in `specs_for&#39;
  /var/lib/gems/2.3.0/gems/bundler-1.16.0/lib/bundler/definition.rb:226:in `requested_specs&#39;
  /var/lib/gems/2.3.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:108:in `block in definition_method&#39;
  /var/lib/gems/2.3.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:20:in `setup&#39;
  /var/lib/gems/2.3.0/gems/bundler-1.16.0/lib/bundler.rb:107:in `setup&#39;
  /var/lib/gems/2.3.0/gems/bundler-1.16.0/lib/bundler/setup.rb:20:in `&lt;top (required)&gt;&#39;
  /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require&#39;
  /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require&#39;
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:430:in `activate_gem&#39;
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:297:in `block in run_load_path_setup_code&#39;
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:435:in `running_bundler&#39;
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:296:in `run_load_path_setup_code&#39;
  /usr/share/passenger/helper-scripts/rack-preloader.rb:100:in `preload_app&#39;
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `&lt;module:App&gt;&#39;
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `&lt;module:PhusionPassenger&gt;&#39;
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `&lt;main&gt;&#39;</pre>


[ 2017-12-14 02:29:07.5565 1386/7ff9fafdf700 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 1bbd191a. Please see earlier logs for details about the error.
```

**Comment by serenabenny** [comment]
changed Gemfile to 
```
gem 'rich'
#, git: 'https://github.com/a-ono/rich.git'
gem 'kaminari'
gem 'htmlentities'
gem 'paperclip', '~> 4.2.1'
gem 'pandoc-ruby'

# It is needed for upgrading CKEditor
#gem 'sprockets-rails', '< 3.0.0'
```

```
bennylam_serena@redmine:/opt/redmine/redmine$ bundle install
Fetching gem metadata from http://rubygems.org/...............
Fetching version metadata from http://rubygems.org/...
Fetching dependency metadata from http://rubygems.org/..
Fetching gem metadata from http://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/...............
Fetching version metadata from http://rubygems.org/...
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from http://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies....
Using rake 12.3.0
Using i18n 0.7.0
Using minitest 5.10.3
Using thread_safe 0.3.6
Using builder 3.2.3
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using crass 1.0.3
Using rack 1.6.8
Using mini_mime 1.0.0
Using arel 6.0.4
Using bundler 1.15.1
Using thor 0.20.0
Using concurrent-ruby 1.0.5
Using coderay 1.1.2
Using request_store 1.0.5
Using mime-types-data 3.2016.0521
Using public_suffix 3.0.1
Using mimemagic 0.3.2
Using rubyzip 1.0.0
Using htmlentities 4.3.4
Using rbpdf-font 1.19.1
Using net-ldap 0.12.1
Using ruby-openid 2.3.0
Using rmagick 2.16.0
Using redcarpet 3.4.0
Using mysql2 0.4.10
Using liquid 2.6.3
Using kaminari-core 1.1.1
Using climate_control 0.2.0
Using multi_json 1.12.2
Using rb-fsevent 0.10.2
Using ffi 1.9.18
Using tilt 2.0.8
Using pandoc-ruby 2.0.2
Using ruby-ole 1.2.12.1
Using dalli 2.7.6
Using memcachier 0.0.2
Using tzinfo 1.2.4
Using nokogiri 1.7.2
Using rack-test 0.6.3
Using mail 2.7.0
Using sprockets 3.7.1
Using mime-types 3.1
Using addressable 2.5.2
Using zip-zip 0.3
Using rbpdf 1.19.3
Using rack-openid 1.4.2
Using redmine_crm 0.0.32
Using cocaine 0.5.8
Using rack-raw-upload 1.1.1
Using rb-inotify 0.9.10
Using spreadsheet 1.1.5
Using activesupport 4.2.8
Using loofah 2.1.1
Using axlsx 2.0.1
Using css_parser 1.6.0
Using sass-listen 4.0.0
Using roo 1.13.2
Using rails-deprecated_sanitizer 1.0.3
Using globalid 0.4.1
Using activemodel 4.2.8
Using rails-html-sanitizer 1.0.3
Using roadie 3.2.2
Using sass 3.5.3
Using rails-dom-testing 1.0.8
Using activejob 4.2.8
Using activerecord 4.2.8
Using protected_attributes 1.1.4
Using paperclip 4.2.4
Using actionview 4.2.8
Using kaminari-activerecord 1.1.1
Using actionpack 4.2.8
Using kaminari-actionview 1.1.1
Using actionmailer 4.2.8
Using railties 4.2.8
Using sprockets-rails 3.2.1
Using actionpack-xml_parser 1.0.2
Using axlsx_rails 0.5.1
Using kaminari 1.1.1
Using jquery-rails 3.1.4
Using roadie-rails 1.1.1
Using rails 4.2.8
Using sass-rails 5.0.7
Using rich 1.4.6 (was 1.4.8)
Bundle complete! 43 Gemfile dependencies, 85 gems now installed.
Gems in the groups development, test, test/[A, postgresql and sqlite were not installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```
**Error Log**
```
[ 2017-12-14 03:13:49.9263 1386/7ffa025d0700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /opt/redmine/redmine: An error occurred while starting up the preloader.
  Error ID: b5c281f4
  Error details saved to: /tmp/passenger-error-E8XC2s.html
  Message from application: The scope body needs to be callable. (ArgumentError)
  /var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/scoping/named.rb:143:in `scope'
  /var/lib/gems/2.3.0/gems/rich-1.4.6/app/models/rich/rich_file.rb:10:in `<class:RichFile>'
  /var/lib/gems/2.3.0/gems/rich-1.4.6/app/models/rich/rich_file.rb:6:in `<module:Rich>'
  /var/lib/gems/2.3.0/gems/rich-1.4.6/app/models/rich/rich_file.rb:5:in `<top (required)>'
  /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
  /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
  /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
  /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
  /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:360:in `require_or_load'
  /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:317:in `depend_on'
  /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:233:in `require_dependency'
  /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
  /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:471:in `each'
  /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:471:in `block in eager_load!'
  /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:469:in `each'
  /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:469:in `eager_load!'
  /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:346:in `eager_load!'
  /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/application/finisher.rb:56:in `each'
  /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
  /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
  /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
  /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
  /usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
  /usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
  /usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
  /usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
  /usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
  /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
  /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
  /opt/redmine/redmine-3.4.3/config/environment.rb:14:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /var/lib/gems/2.3.0/gems/rack-1.6.8/lib/rack/builder.rb:55:in `instance_eval'
  /var/lib/gems/2.3.0/gems/rack-1.6.8/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'


[ 2017-12-14 03:13:49.9298 1386/7ff9fafdf700 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 1-3] Cannot checkout session because a spawning error occurred. The identifier of the error is b5c281f4. Please see earlier logs for details about the error.
```

**Comment by tiurlumbangaol** [comment]
@serenabenny hi, you need to edit the rich gem, i edit if on : 
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rich-1.4.6/app/models/rich/rich_file.rb

adding this 1 line code : 
`include Backends::Paperclip`

so it will become like this : 
`require 'cgi'
require 'mime/types'
require 'kaminari'

module Rich
  class RichFile < ActiveRecord::Base
include Backends::Paperclip
    attr_accessible :rich_file_file_name, :rich_file_content_type, :rich_file_file_size, :rich_file_updated_at, :owner_type, :owner_id, :uri_cache, :simplified_type
`

**Comment by serenabenny** [comment]
@tiurlumbangaol Thanks for your help, but I tried that solution, also same error.

**Comment by imgooglian** [comment]
Cannot install on 3.4.4 as well, I am using the official docker image

**Comment by playmyskay** [comment]
running the following command works for me: 
`bundle config --delete frozen`

if you are using a docker image then connect to bash (redmine is your container name):
`docker exec -it redmine bash`

**Comment by a-ono** [comment]
Please try version 1.1.7 or 1.2.0.
