### ISSUE TITLE
ActionView::Template::Error (Permission denied @ dir_s_mkdir - /usr/share/redmine/instances/default/tmp/cache)

### ISSUE THREAD

**Issue by ZerooCool** [a-ono/redmine_ckeditor#287]
```
 Rendered my/account.html.erb within layouts/base (840.9ms)
Completed 500 Internal Server Error in 864ms (ActiveRecord: 9.8ms)
ActionView::Template::Error (Permission denied @ dir_s_mkdir - /usr/share/redmine/instances/default/tmp/cache):
    22:   <p><%= f.text_field :lastname, :required => true %></p>
    23:   <p><%= f.text_field :mail, :required => true %></p>
    24:   <% unless @user.force_default_language? %>
    25:   <p><%= f.select :language, lang_options_for_select %></p>
    26:   <% end %>
    27:   <% if Setting.openid? %>
    28:   <p><%= f.text_field :identity_url  %></p>
  lib/redmine/i18n.rb:125:in `languages_options'
  app/helpers/application_helper.rb:1180:in `lang_options_for_select'
  app/views/my/account.html.erb:25:in `block in _app_views_my_account_html_erb___1888147871918549386_70193739725340'
  app/helpers/application_helper.rb:1190:in `labelled_form_for'
  app/views/my/account.html.erb:14:in `_app_views_my_account_html_erb___1888147871918549386_70193739725340'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by ZerooCool** [comment]
sudo mkdir /usr/share/redmine/instances/default/tmp/cache
cd /usr/share/redmine/instances/default/tmp
sudo chown -R redmine:redmine cache/
sudo chmod -R 755 cache/
