### ISSUE TITLE
install successful but do not enter redmine setting page.

### ISSUE THREAD

**Issue by yung555** [a-ono/redmine_ckeditor#299]
Hello.
I installed redmine_ckeditor on docker and restart redmine container.
and, in redmine page successfully enter and login, but click settings tabs, redmine showed internal error page.
how to solve this problem?
thanks.
Logs
```
I, [2019-04-11T01:20:46.696205 #1]  INFO -- : Completed 500 Internal Server Error in 21ms (ActiveRecord: 3.8ms)
F, [2019-04-11T01:20:46.696815 #1] FATAL -- :
F, [2019-04-11T01:20:46.696830 #1] FATAL -- : ActionView::Template::Error (uninitialized constant #<Class:RedmineCkeditor>::RedmineCkeditorSetting):
F, [2019-04-11T01:20:46.696897 #1] FATAL -- :     4: <p><%= setting_text_field :app_title, :size => 30 %></p>
    5:
    6: <p><%= setting_text_area :welcome_text, :cols => 60, :rows => 5, :class => 'wiki-edit' %></p>
    7: <%= wikitoolbar_for 'settings_welcome_text' %>
    8:
    9:
   10: <p><%= setting_text_field :per_page_options, :size => 20 %>
F, [2019-04-11T01:20:46.696905 #1] FATAL -- :
F, [2019-04-11T01:20:46.696913 #1] FATAL -- : plugins/redmine_ckeditor-master/lib/redmine_ckeditor.rb:97:in `options'
plugins/redmine_ckeditor-master/lib/redmine_ckeditor/wiki_formatting/helper.rb:11:in `replace_editor_script'
plugins/redmine_ckeditor-master/lib/redmine_ckeditor/wiki_formatting/helper.rb:49:in `wikitoolbar_for'
app/views/settings/_general.html.erb:7:in `block in _app_views_settings__general_html_erb__269332489029538010_47443482090080'
app/views/settings/_general.html.erb:1:in `_app_views_settings__general_html_erb__269332489029538010_47443482090080'
app/views/common/_tabs.html.erb:17:in `block in _app_views_common__tabs_html_erb__168465541781978862_47443482027400'
app/views/common/_tabs.html.erb:16:in `each'
app/views/common/_tabs.html.erb:16:in `_app_views_common__tabs_html_erb__168465541781978862_47443482027400'
app/helpers/application_helper.rb:386:in `render_tabs'
app/views/settings/edit.html.erb:5:in `_app_views_settings_edit_html_erb___3870237135444545812_47443482013240'
app/controllers/settings_controller.rb:31:in `index'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

Environment.
```
docker 18.09.4
redmine : 4.0.3
ruby : 2.6.2
Rail : 5.2.2.1
redmine_ckeditor : 1.2.1
```

**Comment by miiinee** [comment]
I have same problem and I got some hints from other plugins.
rename your folder in plugins/. (redmine_ckeditor-master -> redmine_ckeditor)
and then I solve the problem.
