### ISSUE TITLE
Error while configuring the plugin

### ISSUE THREAD

**Issue by CSCSxx** [a-ono/redmine_ckeditor#344]
I just set up a new system using a Sameersbn Redmine Docker Image.
Special features: Different editors, project-dependent use (via plugin)
The CK Editor itself seems to be working, I was able to successfully create tickets.
However, trying to configure the editor under Administration->Plugins fails.

**System Info:**
  Redmine version                4.2.3.stable
  Ruby version                   2.6.6-p146 (2020-03-31) [x86_64-linux-gnu]
  Rails version                  5.2.6
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.13.0
  Mercurial                      5.3.1
  Cvs                            1.12.13
  Bazaar                         3.0.2
  Git                            2.33.1
  Filesystem                     
Redmine plugins:
  additionals                    3.0.5-master
  redmine_agile                  1.6.2
  redmine_checklists             3.1.20
  redmine_ckeditor               1.2.3
  redmine_cms                    1.2.2
  redmine_contacts               4.3.4
  redmine_contacts_helpdesk      4.1.12
  redmine_dmsf                   2.4.11
  redmine_drive                  1.1.1
  redmine_people                 1.6.1
  redmine_per_project_formatting 0.1.0
  redmine_questions              1.0.2
  redmine_reporter               2.0.1
  redmine_resources              1.0.6
  redmine_wktime                 4.4.1
  redmine_wysiwyg_editor         0.23.0
  redmine_zenedit                2.0.2
  redmineup_tags                 2.0.11
  vault                          0.4.3

**Error Message:**
Started GET "/settings/plugin/redmine_ckeditor" for 127.0.0.1 at 2022-01-28 12:00:44 +0000
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_ckeditor"}
  Current user: admin (id=1)
  Rendering settings/plugin.html.erb within layouts/admin
  Rendered plugins/redmine_ckeditor/app/views/settings/_ckeditor.html.erb (1561.4ms)
  Rendered settings/plugin.html.erb within layouts/admin (1564.5ms)
Completed 500 Internal Server Error in 1948ms (ActiveRecord: 151.0ms)
  
ActionView::Template::Error (undefined local variable or method `ckeditor_javascripts' for #<#<Class:0x00007f3eb0998360>:0x00007f3eb0d5f4f8>):
    1: <%= ckeditor_javascripts %>
    2: <%= stylesheet_link_tag 'editor', :plugin => 'redmine_ckeditor'%>
    3: <%= stylesheet_link_tag 'selector', :plugin => 'redmine_ckeditor'%>
    4: <p>
  
plugins/redmine_ckeditor/app/views/settings/_ckeditor.html.erb:1:in `_plugins_redmine_ckeditor_app_views_settings__ckeditor_html_erb__282186640417499865_69953594841420'
app/views/settings/plugin.html.erb:6:in `block in _app_views_settings_plugin_html_erb__3354318643736265320_69953613775960'
app/views/settings/plugin.html.erb:4:in `_app_views_settings_plugin_html_erb__3354318643736265320_69953613775960'
plugins/redmine_per_project_formatting/lib/redmine_per_project_formatting/application_controller_patch.rb:24:in `block in change_text_formatting'
plugins/redmine_per_project_formatting/lib/redmine_per_project_formatting/setting_patch.rb:19:in `within_text_formatting'
plugins/redmine_per_project_formatting/lib/redmine_per_project_formatting/application_controller_patch.rb:23:in `change_text_formatting'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:56:in `call'

**Comment by DeaconF** [comment]
Had the same problem, this quickfix worked for me:
https://github.com/a-ono/redmine_ckeditor/pull/296/commits/ba7d8b58ea12d88f1aaba01a8183d849e63954d0

**Comment by CSCSxx** [comment]
Cool, works also for me!
Thank you :)

Should urgently be migrated to the current version!

**Comment by JonYeb** [comment]
Worked for me, had the same issue before. Thanks.
