### ISSUE TITLE
CK Editor Is Alive For Redmine 5!

### ISSUE THREAD

**Issue by michaelstanek** [a-ono/redmine_ckeditor#352]
At RedmineX, we took over this project and we are humbled we can continue developing this plugin which will be FREE forever for the Redmine community. [Download CK Editor for Redmine 5](https://www.redmine.org/plugins/redmine-x-ck-editor-free)

**Comment by MasyGreen** [comment]
Gerat!!!

**Comment by blackbart420** [comment]
Hello @michaelstanek ,
thank you!

I just tried to install it, but the module redmine x ckeditor is not working on redmine 5.0.3 as this guy mentionned here 10 ago in the comment:
https://www.redmine.org/plugins/redmine-x-ck-editor-free

I get the same error.

Where can I file an issue for the plugin?

**Comment by blackhase** [comment]
This fork work with redmine 5.0.3.stable,

https://github.com/nomadli/redmine_ckeditor 

Thnak on @nomadli.

**Comment by blackbart420** [comment]
Thank you @blackhase , it works!

**Comment by qawsed55** [comment]
Plugin from Remine-X do not work correctly.
In log - there are errors:
```
 INFO -- : [10ffb03e-b52f-4fd5-9b12-2df2c1b7acea] Started GET "/plugin_assets/redmine_ckeditor/ckeditor/plugins/scayt/skins/kama/scayt.css?t=KA9B" for 192.168.3.222 at 2023-03-11 18:51:25 +0300
FATAL -- : [10ffb03e-b52f-4fd5-9b12-2df2c1b7acea]
[10ffb03e-b52f-4fd5-9b12-2df2c1b7acea] ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_ckeditor/ckeditor/plugins/scayt/skins/kama/scayt.css"):
[10ffb03e-b52f-4fd5-9b12-2df2c1b7acea]
 INFO -- : [fbcf8341-c336-4769-abfe-e030dc35208c] Started GET "/plugin_assets/redmine_ckeditor/ckeditor/plugins/wsc/skins/kama/wsc.css?t=KA9B" for 192.168.3.222 at 2023-03-11 18:51:25 +0300
[fbcf8341-c336-4769-abfe-e030dc35208c] ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_ckeditor/ckeditor/plugins/wsc/skins/kama/wsc.css"):
```

Also, when I set this editor in settings - many macroses do not work (like DMS, mermaid)

**Comment by sylvainfaivre** [comment]
Hello @michaelstanek 

I tried reaching out to anna at redmine-x.com 3 weeks ago but got no answer, so I post here in hope you will see it :

> 
> It's nice that you forked the Redmine CKEditor plugin for Redmine 5 and released it for free, but it seems that there is no way to reach you for support regarding this plugin on your website, as a login is needed to access the support forums, and a subscription is needed for this.
> 
> As you forked it from a github project, the easiest solution may be to host your fork on Github too. What do you think about that ?
> 
> By the way, I contacted you because I hit this bug : https://github.com/a-ono/redmine_ckeditor/issues/345
> 
> The bug is also present on your fork, and I commented on the issue with a fix, so I wanted to make you aware of this so that you can review the fix and merge it into your fork.

Additionally, we also experiment a new bug with your version of the plugin, the PDF export fails for issues that have a picture attached by the plugin. See start of stack trace below : 

```
I, [2023-12-07T17:35:11.333255 #96778]  INFO -- : [207eca14-bb8f-4489-bb6f-8844956adaa4] Started GET "/issues/123456789.pdf" for 1.1.1.1 at 2023-12-07 17:35:11 +0100
I, [2023-12-07T17:35:11.335195 #96778]  INFO -- : [207eca14-bb8f-4489-bb6f-8844956adaa4] Processing by IssuesController#show as PDF
I, [2023-12-07T17:35:11.335343 #96778]  INFO -- : [207eca14-bb8f-4489-bb6f-8844956adaa4]   Parameters: {"id"=>"123456789"}
I, [2023-12-07T17:35:11.345647 #96778]  INFO -- : [207eca14-bb8f-4489-bb6f-8844956adaa4]   Current user: user61 (id=61)
E, [2023-12-07T17:35:11.669781 #96778] ERROR -- : [207eca14-bb8f-4489-bb6f-8844956adaa4] pdf: writeHTML: undefined method `decode' for URI:Module
E, [2023-12-07T17:35:11.670394 #96778] ERROR -- : [207eca14-bb8f-4489-bb6f-8844956adaa4] /data/redmine/plugins/redmine_ckeditor/lib/redmine_ckeditor/pdf_patch.rb:41:in `get_image_filename'
E, [2023-12-07T17:35:11.670525 #96778] ERROR -- : [207eca14-bb8f-4489-bb6f-8844956adaa4] /data/redmine/.rvm/gems/ruby-3.2.2/gems/rbpdf-1.21.3/lib/rbpdf.rb:14315:in `openHTMLTagHandler'
E, [2023-12-07T17:35:11.670652 #96778] ERROR -- : [207eca14-bb8f-4489-bb6f-8844956adaa4] /data/redmine/.rvm/gems/ruby-3.2.2/gems/rbpdf-1.21.3/lib/rbpdf.rb:13924:in `writeHTML'
E, [2023-12-07T17:35:11.670740 #96778] ERROR -- : [207eca14-bb8f-4489-bb6f-8844956adaa4] /data/redmine/.rvm/gems/ruby-3.2.2/gems/rbpdf-1.21.3/lib/rbpdf.rb:3940:in `MultiCell'
E, [2023-12-07T17:35:11.670828 #96778] ERROR -- : [207eca14-bb8f-4489-bb6f-8844956adaa4] /data/redmine/.rvm/gems/ruby-3.2.2/gems/rbpdf-1.21.3/lib/rbpdf.rb:12983:in `writeHTMLCell'
E, [2023-12-07T17:35:11.670900 #96778] ERROR -- : [207eca14-bb8f-4489-bb6f-8844956adaa4] /data/redmine/lib/redmine/export/pdf.rb:95:in `RDMwriteFormattedCell'
E, [2023-12-07T17:35:11.670990 #96778] ERROR -- : [207eca14-bb8f-4489-bb6f-8844956adaa4] /data/redmine/lib/redmine/export/pdf/issues_pdf_helper.rb:229:in `block in issue_to_pdf'
E, [2023-12-07T17:35:11.671150 #96778] ERROR -- : [207eca14-bb8f-4489-bb6f-8844956adaa4] /data/redmine/lib/redmine/export/pdf/issues_pdf_helper.rb:215:in `each'
E, [2023-12-07T17:35:11.671256 #96778] ERROR -- : [207eca14-bb8f-4489-bb6f-8844956adaa4] /data/redmine/lib/redmine/export/pdf/issues_pdf_helper.rb:215:in `issue_to_pdf'
```
